import { StyleSheet, Dimensions } from "react-native";
import { theme } from "../../global/theme";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.primary,
  },
  backgroudImg: {
    flex: 1,
    width: "100%",
    opacity: 0.9,
  },
  form: {
    flex: 1,
    backgroundColor: theme.colors.gray[100],
    borderTopLeftRadius: width * 0.08,
    borderTopRightRadius: width * 0.08,
    paddingHorizontal: width * 0.06,
    paddingTop: height * 0.03,
  },
  sectionTitle: {
    fontSize: width * 0.06,
    fontFamily: theme.fonts.title700,
    color: theme.colors.primary,
    marginTop: height * 0.03,
    marginBottom: height * 0.025,
    borderLeftWidth: 4,
    borderLeftColor: theme.colors.primary,
    paddingLeft: width * 0.03,
  },
  footer: {
    marginTop: "auto",
    paddingVertical: height * 0.03,
    backgroundColor: theme.colors.gray[100],
    alignItems: "center",
  },
  inputGroup: {
    marginBottom: height * 0.025,
  },
  input: {
    backgroundColor: "#fff",
    borderRadius: width * 0.03,
    borderWidth: 1,
    borderColor: theme.colors.gray[200],
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.018,
    fontSize: width * 0.045,
    color: theme.colors.text,
    fontFamily: theme.fonts.text400,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: width * 0.04,
    marginBottom: height * 0.02,
  },
  rowItem: {
    flex: 1,
  },
  errorText: {
    color: theme.colors.error,
    fontSize: width * 0.03,
    fontFamily: theme.fonts.text400,
    marginTop: 4,
    marginLeft: 4,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: theme.colors.gray[200],
    marginVertical: height * 0.03,
  },
  buttonContainer: {
    width: "100%",
    alignItems: "center",
  },
  primaryButton: {
    width: "100%",
    backgroundColor: theme.colors.primary,
    borderRadius: width * 0.03,
    paddingVertical: height * 0.022,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 3.84,
    marginTop: height * 0.01,
  },
  primaryButtonText: {
    color: "#fff",
    fontFamily: theme.fonts.title700,
    fontSize: width * 0.05,
    letterSpacing: 1,
  },
  secondaryButton: {
    width: "100%",
    backgroundColor: theme.colors.gray[300],
    borderWidth: 1,
    borderColor: theme.colors.gray[300],
    borderRadius: width * 0.03,
    paddingVertical: height * 0.02,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 1.41,
    marginTop: height * 0.01,
  },
  secondaryButtonText: {
    color: theme.colors.primary,
    fontFamily: theme.fonts.title700,
    fontSize: width * 0.045,
    letterSpacing: 1,
  },
  confirmationContainer: {
    backgroundColor: theme.colors.gray[100],
    borderRadius: width * 0.03,
    padding: width * 0.05,
    marginTop: height * 0.025,
    borderWidth: 1,
    borderColor: theme.colors.gray[200],
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
  },
  confirmationTitle: {
    fontSize: width * 0.045,
    fontFamily: theme.fonts.title700,
    color: theme.colors.text,
    marginBottom: height * 0.015,
  },
  confirmationText: {
    fontSize: width * 0.038,
    fontFamily: theme.fonts.text400,
    color: theme.colors.text,
    marginBottom: 8,
    lineHeight: 22,
  },
});
