version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: quick
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - .data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --maxmemory 25mb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=suasenhaaqui
    ports:
      - "6379:6379"
    restart: unless-stopped

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8083:8081"
    command: [
      "--host=postgres",
      "--user=postgres",
      "--pass=mysecretpassword",
      "--db=quick",
       "--ssl=disable"  
    ]
    depends_on:
      - postgres

volumes:
  postgres_data:


networks:
  defaults:
    name: minha_rede
    driver: bridge
