version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword # Troque por uma senha segura em produção!
      POSTGRES_DB: quick
    ports:
      - "5432:5432"
    volumes:
      - .data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # URL de acesso: postgresql://postgres:mysecretpassword@localhost:5432/quick

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: youruser     # Troque em produção
      RABBITMQ_DEFAULT_PASS: yourpassword # Troque em produção
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
    # URLs de acesso:
    # - Interface web: http://localhost:15672 (usuário: youruser, senha: yourpassword)
    # - Conexão AMQP: amqp://youruser:yourpassword@localhost:5672/

volumes:
  postgres_data: