export const deliveryLabels: Record<string, string> = {
  id: "ID",
  code: "Código",
  height: "Altura (cm)",
  width: "Largura (cm)",
  length: "Comprimento (cm)",
  weight: "Peso (kg)",
  information: "Informações",
  isFragile: "Frágil",
  price: "Preço",
  companyId: "ID da Empresa",
  email: "Email",
  telefone: "Telefone",
  status: "Status",
  completedAt: "Concluído em",
  deliveryManId: "ID do Entregador",
  vehicleType: "Tipo de Veículo",
  DeliveryMan: "Entregador",
  Routes: "Rotas",
}
